// Temporary sample data so the UI is browsable before real data is seeded
// into Supabase. Swap each usage for a real Supabase query — see the
// commented examples in app/search/page.tsx and app/opportunities/[id]/page.tsx.
import type { Opportunity } from '@/types/database.types';

const org = (name: string) => ({
  id: name,
  owner_id: null,
  name,
  description: null,
  website: null,
  contact_email: null,
  contact_phone: null,
  logo_url: null,
  is_verified: true,
  created_at: '',
  updated_at: '',
});

const cat = (slug: string, name: string) => ({ id: slug, slug, name, icon: null });

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    organization_id: 'org1',
    submitted_by: null,
    title: 'Weekend Animal Shelter Helper',
    description:
      'Help walk dogs, clean kennels, and socialize cats at our no-kill shelter. Great for animal lovers looking for a recurring weekend commitment.',
    location_type: 'in_person',
    address: null,
    city: 'Tempe',
    state: 'AZ',
    zip: '85281',
    latitude: null,
    longitude: null,
    commitment_type: 'recurring',
    start_date: '2026-09-20',
    end_date: null,
    recurring_schedule: 'Every Saturday, 9–11am',
    estimated_hours: 2,
    min_age: 14,
    max_age: null,
    requires_guardian_consent: true,
    spots_available: 6,
    application_url: null,
    application_instructions: null,
    status: 'verified',
    rejection_reason: null,
    verified_at: '2026-09-01',
    verified_by: null,
    expires_at: null,
    view_count: 0,
    created_at: '',
    updated_at: '',
    organization: org('Desert Paws Animal Shelter'),
    categories: [cat('animals', 'Animals & Wildlife')],
  },
  {
    id: '2',
    organization_id: 'org2',
    submitted_by: null,
    title: 'Virtual Math Tutor for Middle Schoolers',
    description:
      'Tutor 6th–8th graders in algebra basics over video call. Flexible scheduling, training materials provided.',
    location_type: 'virtual',
    address: null,
    city: null,
    state: null,
    zip: null,
    latitude: null,
    longitude: null,
    commitment_type: 'recurring',
    start_date: '2026-09-15',
    end_date: '2027-05-30',
    recurring_schedule: '1 hour per week, schedule with student',
    estimated_hours: 1,
    min_age: 15,
    max_age: null,
    requires_guardian_consent: false,
    spots_available: 20,
    application_url: null,
    application_instructions: null,
    status: 'verified',
    rejection_reason: null,
    verified_at: '2026-08-28',
    verified_by: null,
    expires_at: null,
    view_count: 0,
    created_at: '',
    updated_at: '',
    organization: org('BrightPath Tutoring Network'),
    categories: [cat('education', 'Education & Tutoring')],
  },
  {
    id: '3',
    organization_id: 'org3',
    submitted_by: null,
    title: 'Community Food Bank Sorting Day',
    description:
      'One-day event sorting and packing donated food for local families ahead of the holidays. No experience needed.',
    location_type: 'in_person',
    address: null,
    city: 'Mesa',
    state: 'AZ',
    zip: '85201',
    latitude: null,
    longitude: null,
    commitment_type: 'one_time',
    start_date: '2026-11-14',
    end_date: '2026-11-14',
    recurring_schedule: null,
    estimated_hours: 4,
    min_age: 12,
    max_age: null,
    requires_guardian_consent: true,
    spots_available: 40,
    application_url: null,
    application_instructions: null,
    status: 'verified',
    rejection_reason: null,
    verified_at: '2026-09-05',
    verified_by: null,
    expires_at: null,
    view_count: 0,
    created_at: '',
    updated_at: '',
    organization: org('Valley Food Bank'),
    categories: [cat('food_insecurity', 'Food Insecurity')],
  },
];
